export const environment = {
  production: true,
  APIURL: 'http://localhost:3000',
  endPoint: 'https://localhost:7094/api/',
  domain: 'https://localhost:7094/',
  Admin: () => environment.endPoint + 'Admins',
  Companies: () => environment.endPoint + 'Companies',
  User: () => environment.endPoint + 'Users',
  Favourites: () => environment.endPoint + 'Favourites',
  categorywithPost: () => environment.endPoint + 'Categories/withPosts',
  AllCategories: () => environment.endPoint + 'Categories',
  getRandomImages: () => environment.endPoint + 'Images',
  getPost: () => environment.endPoint + 'Posts',
  getcities: () => environment.endPoint + 'Governorates',
  DefaultIMG: '../../../../assets/images/default.jpg',
  Gender: (gender: boolean | null) => (gender ? 'Male' : 'Female'),
};
